### ISSUE TITLE
Unability to log into my corporate account via Linux app

### ISSUE THREAD

**Issue by banderlog** [OfficeDev/microsoft-teams-company-communicator-app#141]
Hi,

I am unable to log into my corporate account via Teams on Ubuntu 18.04 LTS with `teams_1.2.00.32451_amd64.deb`.

On third login page (after "Taking you to your organization's sign-in page" step) there is an inactive "Submit" button:
![](https://gxcuf89792.i.lithium.com/t5/image/serverpage/image-id/163352i51AF5C7D241580C1/image-size/medium?v=1.0&px=400)

Button push (after correct input of login\password) produces next error in console:

```
(node:1778) UnhandledPromiseRejectionWarning: Error: Unknown or unsupported transport “disabled” for address “disabled:”
(node:1778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by rashmi-dixit** [comment]
Just to confirm once, are you trying to login into teams client or signin into company communicator tab in team?

**Comment by banderlog** [comment]
I am trying to login into teams

**Comment by rashmi-dixit** [comment]
Sorry but we won't be able to help as this is more of a login issue with Teams. Only company communicator app template related issues are addressed here.

**Comment by banderlog** [comment]
@rashmi-dixit ok, can you point me to place where I can complain on described problem?

**Comment by rashmi-dixit** [comment]
Please post this on Teams UserVoice.
https://microsoftteams.uservoice.com/

(Under the Give feedback section, where it says Bug Reports)
