### ISSUE TITLE
Deployment Guide Step 3-14

### ISSUE THREAD

**Issue by alexlu0819** [OfficeDev/microsoft-teams-company-communicator-app#144]
In the deployment guide step 3, item 14. Repeat the previous two steps, but with client ID = 1fec8e78-bce4-4aaf-ab1b-5451cc387264. May I know where this client ID is from?

**Comment by rashmi-dixit** [comment]
Per Step3 #12 & 14 - There are two client applications (5e3ce6c0-2b1f-4285-8d4b-75ee78787346 and 1fec8e78-bce4-4aaf-ab1b-5451cc387264) added under "Authorized client applications".

client id '1fec8e78-bce4-4aaf-ab1b-5451cc387264' - To allow application to work in Microsoft Teams Desktop client, 

client id '5e3ce6c0-2b1f-4285-8d4b-75ee78787346' - To allow application to work in Microsoft Teams Web client
