### ISSUE TITLE
Is the content of the Known-limitations page old?

### ISSUE THREAD

**Issue by HiroshiYoshino** [OfficeDev/microsoft-teams-company-communicator-app#146]
In the following document, "Message throttling" and "No retries" are considered current restrictions. 
https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Known-limitations

But with the following fix, retries seem to be already implemented.
https://github.com/OfficeDev/microsoft-teams-company-communicator-app/pull/123

If it's not my misconception, is the content of the wiki delayed to fix?

**Comment by rashmi-dixit** [comment]
The Known Limitations page has been updated for retries. Please let me know if you see any further discrepancies
