### ISSUE TITLE
Application installation with Microsoft Teams policies

### ISSUE THREAD

**Issue by omg1978** [OfficeDev/microsoft-teams-company-communicator-app#150]
When I install the Company Communicator to multiple users, using Microsoft Teams application / permission policies, the application installs correctly but the user ID (29: XXX) is not registered in the Users table.

If the user manually installs the Company Communicator, the user ID is recorded in the table.

**Comment by rashmi-dixit** [comment]
Can you please share the exact steps how you are installing the company communicator app to multiple users, using permission policies/set up policies (prepinning app)? 
Have you created custom policy and assigned them to multiple users? 
This additional information will help us troubleshoot.

**Comment by omg1978** [comment]
Hi @rashmi-dixit 

I have created in the Microsoft Teams Administration Portal:

1) a new permission policy, with the default settings for all applications (Microsoft, third-party and Tenant) "allow all applications".

2) I have created a new set up policy, where I have only "fixed" the Company Communicator application.
