### ISSUE TITLE
Not able to upload the users manifest to the managed apps

### ISSUE THREAD

**Issue by pabbinedi** [OfficeDev/microsoft-teams-company-communicator-app#159]
Since in my environment we have blocked to upload custom app for all users, hence the only way is to to upload the company communicator(User) to the manage apps(teams admin console) and apply to all users as side icon. However when i try to add upload the company communicator app i was not able to do so and getting below error

We can't upload the app. Please try again. If you continue to have problems

**Comment by rashmi-dixit** [comment]
Are you trying pre-pinning the app under set up policies from teams admin center?
Please share the detailed steps and error screenshot.

**Comment by MichaelSourbron** [comment]
I have the same issue when uploading the user.zip with manifest.json for the users.

**Comment by rashmi-dixit** [comment]
@Michael - please share the error screenshot.

**Comment by MichaelSourbron** [comment]
> @michael - please share the error screenshot.
it is fixed now.  seems like if you are missing https:// in front of the URL the deployment failed.
    "websiteUrl": "https://xxx",
    "privacyUrl": "https://xxx",
    "termsOfUseUrl": "https://xx"

**Comment by MichaelSourbron** [comment]
@rashmi-dixit 
it is fixed now.  seems like if you are missing https:// in front of the URL the deployment failed.
    "websiteUrl": "https://xxx",
    "privacyUrl": "https://xxx",
    "termsOfUseUrl": "https://xx"

**Comment by rashmi-dixit** [comment]
@Michael - Yes, that's correct. Those urls in manifest.json should prefix "https://"

**Comment by pabbinedi** [comment]
I managed to fix the issue on the same day..yes after changing the prefix it was working
