### ISSUE TITLE
Image Embedding to Message

### ISSUE THREAD

**Issue by pabbinedi** [OfficeDev/microsoft-teams-company-communicator-app#160]
Hi,

I am not sure if this is the right question to ask in this formum or not. We are able to use Company Communicator effectively. However there is a requirement to send the Broad cast with embedded image which works very well with PNG format , however when we copy the Image (Image is stored in shared location which can be accessed through public network) with PDF it's not reflecting in the message Preview
Below are the screen shots of working an working
![image](https://user-images.githubusercontent.com/49221742/80349021-af360a80-887f-11ea-9dd1-69d830905746.png)

Non-Working Scenario
![image](https://user-images.githubusercontent.com/49221742/80349257-0936d000-8880-11ea-8368-f956a4dbc6ae.png)

How i can make other format files to be visible as an Image in Communicator app message while composing.

**Comment by rashmi-dixit** [comment]
It supports image formats only like png, jpg, jpeg, gif. Hope this helps.

**Comment by pabbinedi** [comment]
Is there way to support the PDF format? Also what is the max size of the image that can be embedded as image? and also is there a way to embedded an image which is of size 1.3 Mb?.

**Comment by pabbinedi** [comment]
Do you have any resolution for sending the larger images? I am trying to send the message with the image which has 1755*2139 pixel dimensions which is failing. Do you guys have any resolution for this issue?

**Comment by rashmi-dixit** [comment]
To support PDF , have the link to the PDF inside of the button URL instead.
![image](https://user-images.githubusercontent.com/57787129/81000588-2103ea80-8e64-11ea-876c-2235776d315d.png)

**Comment by aosolis** [comment]
Here are the max dimensions and size for images, from https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#inline-card-images
>Images must be at most 1024×1024 and 1 MB in PNG, JPEG, or GIF format; animated GIF is not officially supported.
