### ISSUE TITLE
Multi-tenant configuration

### ISSUE THREAD

**Issue by csnarain** [OfficeDev/microsoft-teams-company-communicator-app#163]
Is it mandatory to configure this app in AAD as multi-tenant? This app is going to be used by our internal users only, but not sure why the documentation still insists on using a multi-tenant configuration.

**Comment by rashmi-dixit** [comment]
Multi tenant configuration is required for bot to work when there is manual app registration i.e. manually create your own app ID (and password).
For more details please refer important section in the below page:-    
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0#manual-app-registration
