### ISSUE TITLE
Is it possible to embed an Image in summary as well

### ISSUE THREAD

**Issue by kumaranupam21** [OfficeDev/microsoft-teams-company-communicator-app#170]
Is it possible to embed an Image in summary as well, something like this - 

* Just select Raise your hand Raise your hand in the meeting controls.

![alt text](https://support.content.office.net/en-us/media/79eccc99-5ee0-4714-bd01-cf217fb92f34.png "Raise your hand")

* Meeting presenters will also receive a notification that your hand is raised, and they can lower your hand once you've had a chance to talk.

Currently, it appears like this - 

![image](https://user-images.githubusercontent.com/57713084/82341031-321a3300-99f0-11ea-9127-e71a26205b68.png)

**Comment by rashmi-dixit** [comment]
@kumaranupam21 - Just to confirm, is this something you are requesting for new feature (raise your hand) released recently for Teams meeting?

**Comment by kumaranupam21** [comment]
No, that was just an example of the type of communication I want to create where I want to show some image as part of the summary text as well. I tried the markdown, but it doesn't render the referred image.

**Comment by rashmi-dixit** [comment]
In the current version of company communicator, you can not embed images in message summary.
Alternatively, you can use button title/button url while composing messages for sharing more details.
Please refer below link for supported markdown in adaptive cards in Teams:
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html
