### ISSUE TITLE
Bot not tracking the newly installed Team Personal App user id?

### ISSUE THREAD

**Issue by NandaCodeBox** [OfficeDev/microsoft-teams-company-communicator-app#178]
Message are not notified/sent to users who have installed the user Teams app (company-communicator-users). Initially it was worked for two users after that for new users it is not sending messages. In the Author app i can see messages are sent to only two users.

I have checked the Storage table only two entries are there ? as I have installed this "USER" app for three more users its not getting displayed for them?

Could you please help me out asap??

**Comment by NandaCodeBox** [comment]
When we will get update on this ?

**Comment by NandaCodeBox** [comment]
@Subhasish-msft, Please check this issue as well to get more insight.

**Comment by Subhasish-msft** [comment]
Thanks @NandaCodeBox , We are looking into this issue.

**Comment by Josverl** [comment]
@Subhasish-msft , I think this issue has been resolved and can be closed now.

**Comment by Subhasish-msft** [comment]
Thank for the confirmation @Josverl.
