### ISSUE TITLE
Deployment error due to .Net version 3.1.301 SDK on Azure Web App

### ISSUE THREAD

**Issue by timoleo23** [OfficeDev/microsoft-teams-company-communicator-app#181]
The default .Net SDK on Azure Web App has moved to 3.1.301
The current ARM template deployment fails with following error
`{
"status": "Failed",
"error": {
"code": "ResourceDeploymentFailure",
"message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}`

The error comes from the deployment of the .Net app on the web app with the following error message
`Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
Unhandled exception. System.ComponentModel.Win32Exception (5): Access is denied.
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
Failed exitCode=-532462766, command=dotnet restore "D:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln"
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
An error has occurred during web site deployment.
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
Unhandled exception. System.ComponentModel.Win32Exception (5): Access is denied.\r\n   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)\r\n   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)\r\n   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)\r\n   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)\r\nD:\Program Files (x86)\SiteExtensions\Kudu\87.20522.4610\bin\Scripts\starter.cmd deploy.cmd`

A workaround can be found based on the instructiions provided here asking for a specific version of the .Net SDK (3.1.202)
https://stackoverflow.com/questions/62595408/error-access-is-denied-deployment-to-azure-app-services

This unfortunaltely works only if the web app has the 2 verions installed (which may not be the case with new deployments)

**Comment by aosolis** [comment]
Thanks for the report! This has been fixed with #180
