### ISSUE TITLE
Preview different to Actual Message

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-company-communicator-app#182]
![Preview](https://user-images.githubusercontent.com/65241508/86352694-1d22f780-bc5e-11ea-8ea8-f5c27409877e.PNG)
![Actual](https://user-images.githubusercontent.com/65241508/86352698-1dbb8e00-bc5e-11ea-8eef-5023b21eb56a.PNG)

We just wanted to understand why a sent message format is different to the format when previewed?

See attached example

**Comment by JoeSMGraham** [comment]
Hi!

Do you have any idea about this?

**Comment by aosolis** [comment]
The preview in the task module uses the web renderer for adaptive cards, which is slightly different from the one used in Teams. (Indeed there are 3 different renderers: web/desktop, iOS and Android.) We recommend using the "Preview in this channel" function to send the message to the authors channel, so you can check the final rendering of the card on web, iOS and Android, before sending the message.
