### ISSUE TITLE
Exception thrown when SearchM365GroupsAsync returns 25 groups

### ISSUE THREAD

**Issue by sergiorru** [OfficeDev/microsoft-teams-company-communicator-app#196]
When [SearchM365GroupsAsync](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/blob/940279afe9278d785acbd35dfe56f87c22370260/Source/Microsoft.Teams.Apps.CompanyCommunicator.Common/Services/MicrosoftGraph/Groups/GroupsService.cs#L81) results in 25 groups the next steps (AddDistributionGroupAsync and AddSecurityGroupAsync) gonna be called with a Zero resultCount and the return default raises an error on AddRange.

**Comment by sergiorru** [comment]
I submited [PR(195)](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/pull/195) to fix that.

**Comment by aosolis** [comment]
Thanks for the report! This is fixed in the latest release, incorporating the changes from your PR #195.
