### ISSUE TITLE
No option to delete sent messages from Author App

### ISSUE THREAD

**Issue by Sheshank-TCS** [OfficeDev/microsoft-teams-company-communicator-app#205]
I have sent few test messages while testing and now there is no option to delete though those are not sent to all and to my own test team but it reflects in the records. How to clear them.

![image](https://user-images.githubusercontent.com/71570629/93689573-855ed800-faed-11ea-9413-b5c52ade94b7.png)

**Comment by dj1298** [comment]
There is not an option to delete messages from the Authors app. I have seen a few other issues requesting to allow deletions as well.

**Comment by juna-gupta** [comment]
The app template does not support deleting sent messages. 

It appears you want to clear all the past (test) messages, you may choose to clear all entities in the **SentNotifications** partition manually (**NotificationData** table). Refer [Data Store](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Data-stores#notification-data) for more details.

Closing the issue.
