### ISSUE TITLE
Code deployment failure and Sync Error

### ISSUE THREAD

**Issue by kumaranupam21** [OfficeDev/microsoft-teams-company-communicator-app#229]
Hi, While deploying the App, I am receiving the error #1 as explained in this [page](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Troubleshooting#1-code-deployment-failure ). And when I try the suggested solution to Sync, I receive this error. I have already tried multiple times

`Building the client app (this can take several minutes)

> company-communicator@3.0.0 build C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp
> react-scripts build

Creating an optimized production build...
Failed to compile.

EINVAL: invalid argument, rename 'C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\.cache\terser-webpack-plugin\tmp\a19e0c73' -> 'C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\72\4f\753856fa15d4928a0276de6645186d38d22e996364a424f01682974f754ad29decbfb18a7f69fb5fb132b14b41cbffd1d2aebfbf697ebc982d1e59e97ccb'`

**Comment by flpmoreno** [comment]
I am having the same experience and I also tried in two different tenants.

**Comment by VishalMadhvani** [comment]
kudu build log
```
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
Failed to add 'C:\local\UserProfile\.dotnet\tools' to the PATH environment variable. Add this directory to your PATH to use tools installed with 'dotnet tool install'.

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.302

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
  Determining projects to restore...
  Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Common\Microsoft.Teams.Apps.CompanyCommunicator.Common.csproj (in 1.18 min).
  Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\Microsoft.Teams.Apps.CompanyCommunicator.csproj (in 1.18 min).
  Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Send.Func\Microsoft.Teams.Apps.CompanyCommunicator.Send.Func.csproj (in 1.18 min).
  Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj (in 1.18 min).
  Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj (in 21.86 sec).
Restoring npm packages (this can take several minutes)

> node-sass@4.14.1 install C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-ia32-64_binding.node
Download complete
Binary saved to C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass\vendor\win32-ia32-64\binding.node
Caching binary to C:\local\AppData\npm-cache\node-sass\4.14.1\win32-ia32-64_binding.node

> core-js@2.6.11 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\babel-runtime\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> core-js@3.6.5 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\ejs
> node ./postinstall.js

Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)


> node-sass@4.14.1 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass
> node scripts/build.js

Binary found at C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass\vendor\win32-ia32-64\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

added 2217 packages from 962 contributors in 478.114s
Building the client app (this can take several minutes)

> company-communicator@3.0.0 build C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp
> react-scripts build

Creating an optimized production build...
Failed to compile.

EINVAL: invalid argument, rename 'C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\.cache\terser-webpack-plugin\tmp\b3ffebd4' -> 'C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\8b\ef\8e09fe8316bf9be0013bab0f28e21be928afa77fda3e678c54ed9d7cd3782b28fb5859a64fb20579e3d29b4a41da534ef5a177c65f7de711971fa7ddf691'


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! company-communicator@3.0.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the company-communicator@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
Failed exitCode=1, command=npm run build
npm ERR!     C:\local\AppData\npm-cache\_logs\2020-10-29T11_31_47_050Z-debug.log
An error has occurred during web site deployment.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\n\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! company-communicator@3.0.0 build: `react-scripts build`\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the company-communicator@3.0.0 build script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     C:\local\AppData\npm-cache\_logs\2020-10-29T11_31_47_050Z-debug.log\r\nC:\Program Files (x86)\SiteExtensions\Kudu\90.21005.4823\bin\Scripts\starter.cmd deploy.cmd
```

**Comment by mdcodigo** [comment]
> 
> 
> kudu build log
> 
> ```
> Command: deploy.cmd
> Handling ASP.NET Core Web Application deployment.
> Restoring NuGet packages
> Failed to add 'C:\local\UserProfile\.dotnet\tools' to the PATH environment variable. Add this directory to your PATH to use tools installed with 'dotnet tool install'.
> 
> Welcome to .NET Core 3.1!
> ---------------------
> SDK Version: 3.1.302
> 
> Telemetry
> ---------
> The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
> 
> Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
> 
> ----------------
> Explore documentation: https://aka.ms/dotnet-docs
> Report issues and find source on GitHub: https://github.com/dotnet/core
> Find out what's new: https://aka.ms/dotnet-whats-new
> Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
> Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
> Write your first app: https://aka.ms/first-net-core-app
> --------------------------------------------------------------------------------------
>   Determining projects to restore...
>   Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Common\Microsoft.Teams.Apps.CompanyCommunicator.Common.csproj (in 1.18 min).
>   Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\Microsoft.Teams.Apps.CompanyCommunicator.csproj (in 1.18 min).
>   Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Send.Func\Microsoft.Teams.Apps.CompanyCommunicator.Send.Func.csproj (in 1.18 min).
>   Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj (in 1.18 min).
>   Restored C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj (in 21.86 sec).
> Restoring npm packages (this can take several minutes)
> 
> > node-sass@4.14.1 install C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/win32-ia32-64_binding.node
> Download complete
> Binary saved to C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass\vendor\win32-ia32-64\binding.node
> Caching binary to C:\local\AppData\npm-cache\node-sass\4.14.1\win32-ia32-64_binding.node
> 
> > core-js@2.6.11 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\babel-runtime\node_modules\core-js
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> �[96mThank you for using core-js (�[94m https://github.com/zloirock/core-js �[96m) for polyfilling JavaScript standard library!�[0m
> 
> �[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: �[0m
> �[96m>�[94m https://opencollective.com/core-js �[0m
> �[96m>�[94m https://www.patreon.com/zloirock �[0m
> 
> �[96mAlso, the author of core-js (�[94m https://github.com/zloirock �[96m) is looking for a good job -)�[0m
> 
> 
> > core-js@3.6.5 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\core-js
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> 
> > core-js-pure@3.6.5 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\core-js-pure
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> 
> > ejs@2.7.4 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\ejs
> > node ./postinstall.js
> 
> Thank you for installing �[35mEJS�[0m: built with the �[32mJake�[0m JavaScript build tool (�[32mhttps://jakejs.com/�[0m)
> 
> 
> > node-sass@4.14.1 postinstall C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass
> > node scripts/build.js
> 
> Binary found at C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass\vendor\win32-ia32-64\binding.node
> Testing binary
> Binary is fine
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
> 
> added 2217 packages from 962 contributors in 478.114s
> Building the client app (this can take several minutes)
> 
> > company-communicator@3.0.0 build C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp
> > react-scripts build
> 
> Creating an optimized production build...
> Failed to compile.
> 
> EINVAL: invalid argument, rename 'C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\.cache\terser-webpack-plugin\tmp\b3ffebd4' -> 'C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\8b\ef\8e09fe8316bf9be0013bab0f28e21be928afa77fda3e678c54ed9d7cd3782b28fb5859a64fb20579e3d29b4a41da534ef5a177c65f7de711971fa7ddf691'
> 
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! company-communicator@3.0.0 build: `react-scripts build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the company-communicator@3.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> Failed exitCode=1, command=npm run build
> npm ERR!     C:\local\AppData\npm-cache\_logs\2020-10-29T11_31_47_050Z-debug.log
> An error has occurred during web site deployment.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\n\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! company-communicator@3.0.0 build: `react-scripts build`\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the company-communicator@3.0.0 build script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     C:\local\AppData\npm-cache\_logs\2020-10-29T11_31_47_050Z-debug.log\r\nC:\Program Files (x86)\SiteExtensions\Kudu\90.21005.4823\bin\Scripts\starter.cmd deploy.cmd
> ```

Same error.
NPM is giving warnings like: SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

Could probably someone did a change in a Mac and then made a commit hardecoding some package?.

I mean, the ARM template creates a Windows App Service Plan so quite difficult to compile with an app forcing a Darwing OS package.

**Comment by priyank29** [comment]
@kumaranupam21 @mdcodigo @VishalMadhvani @flpmoreno  Could you try and sync it again? Let us know if you face this issue.

**Comment by kumaranupam21** [comment]
> @kumaranupam21 @mdcodigo @VishalMadhvani @flpmoreno Could you try and sync it again? Let us know if you face this issue.

Works now... Thanks for quick fix 👍

**Comment by juna-gupta** [comment]
@kumaranupam21  Thank you for confirming. Closing the issue.

**Comment by flpmoreno** [comment]
> @kumaranupam21 @mdcodigo @VishalMadhvani @flpmoreno Could you try and sync it again? Let us know if you face this issue.

Thank you so much. It has fixes and I can move forward 👍

**Comment by sathishkumar18594** [comment]
@priyank29  Could you please share me with the fix you've provided? I'm also facing the same issue when I generate a build in Jenkins which is running on Azure

**Comment by GabrielPitondo** [comment]
Having the same issue here. I've already resync everything that was possible. But I'm facing the following error:

![Capturar](https://user-images.githubusercontent.com/76107067/235057636-d691be79-d95f-401b-a218-446a55b28f1c.PNG)
