### ISSUE TITLE
Getting Conflict errors while trying to deploy this in our DEV tenant 

### ISSUE THREAD

**Issue by DipanjanGhosh85** [OfficeDev/microsoft-teams-company-communicator-app#233]
Getting Conflict errors while trying to deploy this in our DEV tenant

**Comment by juna-gupta** [comment]
Please follow [this section ](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Troubleshooting#1-code-deployment-failure) in the troubleshooting guide.

**Comment by DipanjanGhosh85** [comment]
We follow the instructions and did setup both the teams app in the tenant but now while posting a message from the author app it's giving forbidden error- failed to get members of team ..we checked the API permissions but they are mapped as given in the deployment guide.

**Comment by juna-gupta** [comment]
@DipanjanGhosh85 Make sure the global admin grants the admin access. Refer [step 4](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Deployment-guide#4-add-permissions-to-your-app).

**Comment by juna-gupta** [comment]
@DipanjanGhosh85 Closing the issue. Re-open if you're still facing the issue.
