### ISSUE TITLE
outline  parameter in json

### ISSUE THREAD

**Issue by Rykimaruh** [OfficeDev/microsoft-teams-company-communicator-app#236]
Is the outline.png required for the manifest or can we omit this?

Do i need to create an outline file with my custom logo.png file?

Can I delete the outline parameter in the json file if it was the case?

**Comment by juna-gupta** [comment]
Icons (color and outline) are required for this app. Check [this](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package#creating-a-manifest) link for more details.
